# Generated by Django 6.1 on 2026-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteoption_footer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoption',
            name='footer_color',
            field=models.CharField(blank=True, default='#1e40af', help_text='Footer background color (hex format, e.g. #1e40af)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteoption',
            name='footer_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Footer text color (hex format, e.g. #ffffff)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteoption',
            name='header_color',
            field=models.CharField(blank=True, default='#1e40af', help_text='Header background color (hex format, e.g. #1e40af)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteoption',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header background image. If not set, uses header_color.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteoption',
            name='header_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Header text color (hex format, e.g. #ffffff)', max_length=7),
        ),
        migrations.AlterField(
            model_name='siteoption',
            name='footer_image',
            field=models.ImageField(blank=True, help_text='Footer background image. If not set, uses footer_color.', null=True, upload_to='site/'),
        ),
    ]
